<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <OutputType>WinExe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Chip8Face</RootNamespace>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../Core/Orrery/Orrery.csproj"/>
        <ProjectReference Include="../../Core/Mechanism/Mechanism.csproj"/>
        <ProjectReference Include="../../Isa/Chip8/Chip8.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4"/>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
    </ItemGroup>

</Project>
