<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mechanism\Mechanism.csproj"/>
        <ProjectReference Include="..\Orrery\Orrery.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Execute\"/>
        <Folder Include="Memory\"/>
    </ItemGroup>

</Project>
